### ISSUE TITLE
Removing the Debug Tag

### ISSUE THREAD

**Issue by piyushkumar12111111** [0x01-itsmurphy/flutter_portfolio_hacktoberfest#9]

**Comment by killJoy-03** [comment]
@piyushkumar12111111  i want to work on this issue

**Comment by piyushkumar12111111** [comment]
@KoolAbhi03  I have done this work

**Comment by piyushkumar12111111** [comment]
Please assign this to me

**Comment by piyushkumar12111111** [comment]
I am giving pull request

**Comment by piyushkumar12111111** [comment]
thx sir

**Comment by piyushkumar12111111** [comment]
Issue solved please refer 
https://github.com/0x01-itsmurphy/flutter_portfolio_hacktoberfest/pull/14

**Comment by 0x01-itsmurphy** [comment]
solved by @piyushkumar12111111
